// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders            : number;
  notPaidOrders             : number;
  paidOrders                : number;
  numberOfClients           : number;
  numberOfProducts          : number;
  productsWithNoInventory   : number;
  productsWithLowInventory  : number;
}
